In [46]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [47]:
iris = datasets.load_iris()

In [48]:
X = iris.data

In [49]:
y = iris.target

In [50]:
from sklearn.neighbors import KNeighborsClassifier

In [51]:
knn = KNeighborsClassifier(n_neighbors = 1)

In [52]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [53]:
knn.predict([[3, 5, 4, 2]])

array([2])

In [54]:
print("Predicted target name:",
     iris['target_names'][knn.predict([[3, 5, 4, 2]])])

Predicted target name: ['virginica']


In [55]:
X_new = np.array([[3, 5, 4, 2]])
print("X_new.shape: ", X_new.shape)

X_new.shape:  (1, 4)


In [56]:
my_predict = knn.predict(X_new)

In [57]:
print("Prediction: ", my_predict)
print("Prediction target name: ",
     iris['target_names'][my_predict])

Prediction:  [2]
Prediction target name:  ['virginica']


In [58]:
X_new = [[3, 5, 4, 2], [5, 4, 3, 2]]
knn.predict(X_new)

array([2, 1])

In [59]:
knn = KNeighborsClassifier(n_neighbors = 3)

In [60]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [61]:
knn.predict(X_new)

array([1, 1])

In [73]:
from sklearn.linear_model import LogisticRegression

In [74]:
lr = LogisticRegression()
lr.fit(X, y)
lr.predict(X_new)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])