In [1]:
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]

In [3]:
accuracy_score(y_true, y_pred)

0.5

In [4]:
accuracy_score(y_true, y_pred, normalize = False)

2

## DataFrame using Pandas

In [5]:
import pandas as pd

In [6]:
data = {'Name': ["জসিম", "করিম", "মিতা", "অন্তরা"],
        'Location' : ["রাজশাহী", "ঢাকা", "রংপুর", "কুষ্টিয়া"],
        'Age' : [24, 13, 53, 33]
       }

In [7]:
frame = pd.DataFrame(data)

In [8]:
display(frame)

Name   Location  Age
0    জসিম    রাজশাহী   24
1    করিম       ঢাকা   13
2    মিতা      রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

In [9]:
display(frame[frame.Age > 30])

Name   Location  Age
2    মিতা      রংপুর   53
3  অন্তরা  কুষ্টিয়া   33

In [10]:
display(frame[frame.Age < 30])

Name Location  Age
0  জসিম  রাজশাহী   24
1  করিম     ঢাকা   13

In [11]:
display(frame[frame.Age > 130])

Empty DataFrame
Columns: [Name, Location, Age]
Index: []

## Array Creating using NumPy

In [12]:
import numpy as np

In [13]:
x = np.array([1, 2, 3, 4, 5, 6])

In [14]:
x

array([1, 2, 3, 4, 5, 6])

In [15]:
y = np.arange(10)

In [16]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
b = a[ :2, 1 :3]

In [19]:
c = a[ :2]

In [20]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
b

array([[2, 3],
       [6, 7]])

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basis Python

In [23]:
def my_f():
    print("Imam Ahasan")

In [24]:
my_f()

Imam Ahasan


In [25]:
def double(x):
    return x * 2

In [26]:
double(3)

6

In [27]:
tel = {'a': 2345, 'b': 9862}

In [28]:
tel['k'] = 765

In [29]:
tel

{'a': 2345, 'b': 9862, 'k': 765}

In [30]:
tel['b']

9862

In [31]:
x = {'Data Science' : 'is my love', 'Python' : 'is my first love'}

for y, x in x.items():
    print(y, x)

Data Science is my love
Python is my first love


In [32]:
w = ['imam', 'apon', 'fatema', 'smile', 'Bangladesh']

for i in w:
    print(i, len(i))

imam 4
apon 4
fatema 6
smile 5
Bangladesh 10


## dir() function

In [33]:
from sklearn import datasets
iris = datasets.load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']